// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oraclenode.proto

package iop

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ValidateRequest_Type int32

const (
	ValidateRequest_unknown     ValidateRequest_Type = 0
	ValidateRequest_block       ValidateRequest_Type = 1
	ValidateRequest_transaction ValidateRequest_Type = 2
)

var ValidateRequest_Type_name = map[int32]string{
	0: "unknown",
	1: "block",
	2: "transaction",
}

var ValidateRequest_Type_value = map[string]int32{
	"unknown":     0,
	"block":       1,
	"transaction": 2,
}

func (x ValidateRequest_Type) String() string {
	return proto.EnumName(ValidateRequest_Type_name, int32(x))
}

func (ValidateRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{8, 0}
}

type SendRRequest struct {
	R                    *RDeal   `protobuf:"bytes,1,opt,name=R,proto3" json:"R,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRRequest) Reset()         { *m = SendRRequest{} }
func (m *SendRRequest) String() string { return proto.CompactTextString(m) }
func (*SendRRequest) ProtoMessage()    {}
func (*SendRRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{0}
}

func (m *SendRRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRRequest.Unmarshal(m, b)
}
func (m *SendRRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRRequest.Marshal(b, m, deterministic)
}
func (m *SendRRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRRequest.Merge(m, src)
}
func (m *SendRRequest) XXX_Size() int {
	return xxx_messageInfo_SendRRequest.Size(m)
}
func (m *SendRRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRRequest proto.InternalMessageInfo

func (m *SendRRequest) GetR() *RDeal {
	if m != nil {
		return m.R
	}
	return nil
}

type RDeal struct {
	R                    []byte   `protobuf:"bytes,1,opt,name=R,proto3" json:"R,omitempty"`
	Index                []byte   `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RDeal) Reset()         { *m = RDeal{} }
func (m *RDeal) String() string { return proto.CompactTextString(m) }
func (*RDeal) ProtoMessage()    {}
func (*RDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{1}
}

func (m *RDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RDeal.Unmarshal(m, b)
}
func (m *RDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RDeal.Marshal(b, m, deterministic)
}
func (m *RDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RDeal.Merge(m, src)
}
func (m *RDeal) XXX_Size() int {
	return xxx_messageInfo_RDeal.Size(m)
}
func (m *RDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_RDeal.DiscardUnknown(m)
}

var xxx_messageInfo_RDeal proto.InternalMessageInfo

func (m *RDeal) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *RDeal) GetIndex() []byte {
	if m != nil {
		return m.Index
	}
	return nil
}

type SendRResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRResponse) Reset()         { *m = SendRResponse{} }
func (m *SendRResponse) String() string { return proto.CompactTextString(m) }
func (*SendRResponse) ProtoMessage()    {}
func (*SendRResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{2}
}

func (m *SendRResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRResponse.Unmarshal(m, b)
}
func (m *SendRResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRResponse.Marshal(b, m, deterministic)
}
func (m *SendRResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRResponse.Merge(m, src)
}
func (m *SendRResponse) XXX_Size() int {
	return xxx_messageInfo_SendRResponse.Size(m)
}
func (m *SendRResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendRResponse proto.InternalMessageInfo

type SendEnrollRequest struct {
	Enroll               *EnrollDeal `protobuf:"bytes,1,opt,name=Enroll,proto3" json:"Enroll,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendEnrollRequest) Reset()         { *m = SendEnrollRequest{} }
func (m *SendEnrollRequest) String() string { return proto.CompactTextString(m) }
func (*SendEnrollRequest) ProtoMessage()    {}
func (*SendEnrollRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{3}
}

func (m *SendEnrollRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEnrollRequest.Unmarshal(m, b)
}
func (m *SendEnrollRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEnrollRequest.Marshal(b, m, deterministic)
}
func (m *SendEnrollRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEnrollRequest.Merge(m, src)
}
func (m *SendEnrollRequest) XXX_Size() int {
	return xxx_messageInfo_SendEnrollRequest.Size(m)
}
func (m *SendEnrollRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEnrollRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEnrollRequest proto.InternalMessageInfo

func (m *SendEnrollRequest) GetEnroll() *EnrollDeal {
	if m != nil {
		return m.Enroll
	}
	return nil
}

type EnrollDeal struct {
	Reputation           int64    `protobuf:"varint,1,opt,name=reputation,proto3" json:"reputation,omitempty"`
	Index                []byte   `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnrollDeal) Reset()         { *m = EnrollDeal{} }
func (m *EnrollDeal) String() string { return proto.CompactTextString(m) }
func (*EnrollDeal) ProtoMessage()    {}
func (*EnrollDeal) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{4}
}

func (m *EnrollDeal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnrollDeal.Unmarshal(m, b)
}
func (m *EnrollDeal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnrollDeal.Marshal(b, m, deterministic)
}
func (m *EnrollDeal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnrollDeal.Merge(m, src)
}
func (m *EnrollDeal) XXX_Size() int {
	return xxx_messageInfo_EnrollDeal.Size(m)
}
func (m *EnrollDeal) XXX_DiscardUnknown() {
	xxx_messageInfo_EnrollDeal.DiscardUnknown(m)
}

var xxx_messageInfo_EnrollDeal proto.InternalMessageInfo

func (m *EnrollDeal) GetReputation() int64 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

func (m *EnrollDeal) GetIndex() []byte {
	if m != nil {
		return m.Index
	}
	return nil
}

type SendEnrollResponse struct {
	EnrollSuccess        bool     `protobuf:"varint,1,opt,name=EnrollSuccess,proto3" json:"EnrollSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEnrollResponse) Reset()         { *m = SendEnrollResponse{} }
func (m *SendEnrollResponse) String() string { return proto.CompactTextString(m) }
func (*SendEnrollResponse) ProtoMessage()    {}
func (*SendEnrollResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{5}
}

func (m *SendEnrollResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEnrollResponse.Unmarshal(m, b)
}
func (m *SendEnrollResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEnrollResponse.Marshal(b, m, deterministic)
}
func (m *SendEnrollResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEnrollResponse.Merge(m, src)
}
func (m *SendEnrollResponse) XXX_Size() int {
	return xxx_messageInfo_SendEnrollResponse.Size(m)
}
func (m *SendEnrollResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEnrollResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEnrollResponse proto.InternalMessageInfo

func (m *SendEnrollResponse) GetEnrollSuccess() bool {
	if m != nil {
		return m.EnrollSuccess
	}
	return false
}

type SendGetEnrollNodesRequest struct {
	GetNodes             bool     `protobuf:"varint,1,opt,name=getNodes,proto3" json:"getNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendGetEnrollNodesRequest) Reset()         { *m = SendGetEnrollNodesRequest{} }
func (m *SendGetEnrollNodesRequest) String() string { return proto.CompactTextString(m) }
func (*SendGetEnrollNodesRequest) ProtoMessage()    {}
func (*SendGetEnrollNodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{6}
}

func (m *SendGetEnrollNodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendGetEnrollNodesRequest.Unmarshal(m, b)
}
func (m *SendGetEnrollNodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendGetEnrollNodesRequest.Marshal(b, m, deterministic)
}
func (m *SendGetEnrollNodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendGetEnrollNodesRequest.Merge(m, src)
}
func (m *SendGetEnrollNodesRequest) XXX_Size() int {
	return xxx_messageInfo_SendGetEnrollNodesRequest.Size(m)
}
func (m *SendGetEnrollNodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendGetEnrollNodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendGetEnrollNodesRequest proto.InternalMessageInfo

func (m *SendGetEnrollNodesRequest) GetGetNodes() bool {
	if m != nil {
		return m.GetNodes
	}
	return false
}

type SendEnrollNodesResponse struct {
	EnrollNodes          []byte   `protobuf:"bytes,1,opt,name=EnrollNodes,proto3" json:"EnrollNodes,omitempty"`
	EnrollSuccess        bool     `protobuf:"varint,2,opt,name=EnrollSuccess,proto3" json:"EnrollSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendEnrollNodesResponse) Reset()         { *m = SendEnrollNodesResponse{} }
func (m *SendEnrollNodesResponse) String() string { return proto.CompactTextString(m) }
func (*SendEnrollNodesResponse) ProtoMessage()    {}
func (*SendEnrollNodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{7}
}

func (m *SendEnrollNodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEnrollNodesResponse.Unmarshal(m, b)
}
func (m *SendEnrollNodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEnrollNodesResponse.Marshal(b, m, deterministic)
}
func (m *SendEnrollNodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEnrollNodesResponse.Merge(m, src)
}
func (m *SendEnrollNodesResponse) XXX_Size() int {
	return xxx_messageInfo_SendEnrollNodesResponse.Size(m)
}
func (m *SendEnrollNodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEnrollNodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEnrollNodesResponse proto.InternalMessageInfo

func (m *SendEnrollNodesResponse) GetEnrollNodes() []byte {
	if m != nil {
		return m.EnrollNodes
	}
	return nil
}

func (m *SendEnrollNodesResponse) GetEnrollSuccess() bool {
	if m != nil {
		return m.EnrollSuccess
	}
	return false
}

type ValidateRequest struct {
	Type                 ValidateRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=iop.ValidateRequest_Type" json:"type,omitempty"`
	Hash                 []byte               `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Size                 int64                `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MinRank              int64                `protobuf:"varint,4,opt,name=minRank,proto3" json:"minRank,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ValidateRequest) Reset()         { *m = ValidateRequest{} }
func (m *ValidateRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateRequest) ProtoMessage()    {}
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{8}
}

func (m *ValidateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateRequest.Unmarshal(m, b)
}
func (m *ValidateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateRequest.Marshal(b, m, deterministic)
}
func (m *ValidateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateRequest.Merge(m, src)
}
func (m *ValidateRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateRequest.Size(m)
}
func (m *ValidateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateRequest proto.InternalMessageInfo

func (m *ValidateRequest) GetType() ValidateRequest_Type {
	if m != nil {
		return m.Type
	}
	return ValidateRequest_unknown
}

func (m *ValidateRequest) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ValidateRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ValidateRequest) GetMinRank() int64 {
	if m != nil {
		return m.MinRank
	}
	return 0
}

type ValidateResponse struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	BlockNumber          int64    `protobuf:"varint,3,opt,name=blockNumber,proto3" json:"blockNumber,omitempty"`
	Signature            []byte   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	R                    []byte   `protobuf:"bytes,5,opt,name=R,proto3" json:"R,omitempty"`
	Reputation           int64    `protobuf:"varint,6,opt,name=reputation,proto3" json:"reputation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateResponse) Reset()         { *m = ValidateResponse{} }
func (m *ValidateResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateResponse) ProtoMessage()    {}
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_904428fa5c40a904, []int{9}
}

func (m *ValidateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateResponse.Unmarshal(m, b)
}
func (m *ValidateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateResponse.Marshal(b, m, deterministic)
}
func (m *ValidateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateResponse.Merge(m, src)
}
func (m *ValidateResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateResponse.Size(m)
}
func (m *ValidateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateResponse proto.InternalMessageInfo

func (m *ValidateResponse) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ValidateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *ValidateResponse) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

func (m *ValidateResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ValidateResponse) GetR() []byte {
	if m != nil {
		return m.R
	}
	return nil
}

func (m *ValidateResponse) GetReputation() int64 {
	if m != nil {
		return m.Reputation
	}
	return 0
}

func init() {
	proto.RegisterEnum("iop.ValidateRequest_Type", ValidateRequest_Type_name, ValidateRequest_Type_value)
	proto.RegisterType((*SendRRequest)(nil), "iop.SendRRequest")
	proto.RegisterType((*RDeal)(nil), "iop.RDeal")
	proto.RegisterType((*SendRResponse)(nil), "iop.SendRResponse")
	proto.RegisterType((*SendEnrollRequest)(nil), "iop.SendEnrollRequest")
	proto.RegisterType((*EnrollDeal)(nil), "iop.EnrollDeal")
	proto.RegisterType((*SendEnrollResponse)(nil), "iop.SendEnrollResponse")
	proto.RegisterType((*SendGetEnrollNodesRequest)(nil), "iop.SendGetEnrollNodesRequest")
	proto.RegisterType((*SendEnrollNodesResponse)(nil), "iop.SendEnrollNodesResponse")
	proto.RegisterType((*ValidateRequest)(nil), "iop.ValidateRequest")
	proto.RegisterType((*ValidateResponse)(nil), "iop.ValidateResponse")
}

func init() { proto.RegisterFile("oraclenode.proto", fileDescriptor_904428fa5c40a904) }

var fileDescriptor_904428fa5c40a904 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x49, 0xd7, 0xb4, 0xdd, 0x6b, 0xb7, 0x66, 0x4f, 0x85, 0x65, 0xd1, 0x34, 0x4d, 0x11,
	0x12, 0x93, 0x10, 0x99, 0x54, 0x0e, 0x13, 0x88, 0xd3, 0x04, 0xe2, 0x56, 0x24, 0x0f, 0x71, 0xe0,
	0xe6, 0x26, 0xd6, 0x16, 0x35, 0xb3, 0x43, 0xec, 0x00, 0xe3, 0xc4, 0xdf, 0xc3, 0x95, 0x7f, 0x10,
	0xe5, 0xc5, 0x69, 0x93, 0xae, 0xdc, 0xec, 0x4f, 0xde, 0x8f, 0xaf, 0x9f, 0xbf, 0x0e, 0x78, 0xaa,
	0xe0, 0x71, 0x26, 0xa4, 0x4a, 0x44, 0x94, 0x17, 0xca, 0x28, 0xdc, 0x4b, 0x55, 0x1e, 0x5e, 0xc0,
	0xe4, 0x46, 0xc8, 0x84, 0x31, 0xf1, 0xad, 0x14, 0xda, 0xa0, 0x0f, 0x0e, 0xf3, 0x9d, 0x73, 0xe7,
	0x62, 0x3c, 0x87, 0x28, 0x55, 0x79, 0xc4, 0xde, 0x0b, 0x9e, 0x31, 0x87, 0x85, 0x2f, 0xc1, 0xa5,
	0x35, 0x4e, 0x9a, 0x90, 0x09, 0x73, 0x18, 0xce, 0xc0, 0x4d, 0x65, 0x22, 0x7e, 0xfa, 0x3d, 0x22,
	0xf5, 0x26, 0x9c, 0xc2, 0x81, 0x2d, 0xab, 0x73, 0x25, 0xb5, 0x08, 0xdf, 0xc1, 0x51, 0x05, 0x3e,
	0xc8, 0x42, 0x65, 0x59, 0xd3, 0xec, 0x05, 0x0c, 0x6a, 0x60, 0x3b, 0x4e, 0xa9, 0x63, 0x8d, 0xa8,
	0xad, 0xfd, 0x1c, 0x5e, 0x03, 0x6c, 0x28, 0x9e, 0x01, 0x14, 0x22, 0x2f, 0x0d, 0x37, 0xa9, 0x92,
	0x94, 0xba, 0xc7, 0x5a, 0xe4, 0x3f, 0x92, 0xde, 0x02, 0xb6, 0x15, 0xd4, 0xba, 0xf0, 0x39, 0x1c,
	0xd4, 0xe4, 0xa6, 0x8c, 0x63, 0xa1, 0x35, 0x95, 0x1b, 0xb1, 0x2e, 0x0c, 0xaf, 0xe0, 0xa4, 0xca,
	0xfd, 0x28, 0x4c, 0xcd, 0x17, 0x2a, 0x11, 0xba, 0x39, 0x45, 0x00, 0xa3, 0x5b, 0x61, 0x08, 0xd9,
	0xec, 0xf5, 0x3e, 0xe4, 0x70, 0xbc, 0x69, 0x6a, 0xb3, 0x6c, 0xe7, 0x73, 0x18, 0xb7, 0xb0, 0x1d,
	0x68, 0x1b, 0x3d, 0xd6, 0xd6, 0xdb, 0xa5, 0xed, 0xaf, 0x03, 0xd3, 0x2f, 0x3c, 0x4b, 0x13, 0x6e,
	0x44, 0x23, 0xe9, 0x15, 0xf4, 0xcd, 0x43, 0x2e, 0xa8, 0xe8, 0xe1, 0xfc, 0x84, 0xc6, 0xba, 0x15,
	0x13, 0x7d, 0x7e, 0xc8, 0x05, 0xa3, 0x30, 0x44, 0xe8, 0xdf, 0x71, 0x7d, 0x67, 0xe7, 0x45, 0xeb,
	0x8a, 0xe9, 0xf4, 0x97, 0xf0, 0xf7, 0x68, 0xbc, 0xb4, 0x46, 0x1f, 0x86, 0xf7, 0xa9, 0x64, 0x5c,
	0xae, 0xfc, 0x3e, 0xe1, 0x66, 0x1b, 0x5e, 0x42, 0xbf, 0xaa, 0x87, 0x63, 0x18, 0x96, 0x72, 0x25,
	0xd5, 0x0f, 0xe9, 0x3d, 0xc1, 0x7d, 0x70, 0x97, 0x99, 0x8a, 0x57, 0x9e, 0x83, 0x53, 0x18, 0x9b,
	0x82, 0x4b, 0xcd, 0xe3, 0xea, 0x86, 0xbc, 0x5e, 0xf8, 0xc7, 0x01, 0x6f, 0xa3, 0xc8, 0x8e, 0xa4,
	0xd1, 0xe1, 0xb4, 0x74, 0xcc, 0xc0, 0xfd, 0x5e, 0xc5, 0xd9, 0xc3, 0xd7, 0x9b, 0x6a, 0x78, 0x54,
	0x7a, 0x51, 0xde, 0x2f, 0x45, 0x61, 0x45, 0xb6, 0x11, 0x9e, 0xc2, 0xbe, 0x4e, 0x6f, 0x25, 0x37,
	0x65, 0x21, 0x48, 0xed, 0x84, 0x6d, 0x40, 0xed, 0x61, 0xb7, 0xf1, 0x70, 0xd7, 0x50, 0x83, 0x6d,
	0x43, 0xcd, 0x7f, 0xf7, 0x00, 0x3e, 0xd1, 0xf3, 0xa9, 0x2e, 0x06, 0x23, 0x70, 0xc9, 0xdc, 0x78,
	0x44, 0x83, 0x6d, 0xbf, 0x9f, 0x00, 0xdb, 0xc8, 0x1e, 0xeb, 0x0a, 0x46, 0xcd, 0x51, 0x71, 0xb6,
	0xeb, 0x2e, 0x82, 0xa7, 0x5b, 0xd4, 0x26, 0xbe, 0x69, 0xde, 0x07, 0x3e, 0x5b, 0x97, 0xed, 0xbc,
	0xa0, 0xe0, 0xf8, 0x11, 0xb7, 0xa9, 0x0b, 0x38, 0xec, 0xba, 0x15, 0xcf, 0xd6, 0xa1, 0x3b, 0x6d,
	0x1c, 0x9c, 0x6e, 0x95, 0xea, 0xb8, 0xf5, 0x7a, 0xf8, 0xd5, 0x8d, 0x2e, 0x53, 0x95, 0x2f, 0x07,
	0xf4, 0xf3, 0x78, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x5e, 0xc1, 0xf9, 0x50, 0x04, 0x00,
	0x00,
}
